// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[slug]" | "/admin" | "/geo-v1"
type AppRouteHandlerRoutes = "/api/admin/originals" | "/api/admin/shapes" | "/api/admin/shapes/[shapeKey]" | "/api/admin/shapes/[shapeKey]/rebuild" | "/api/admin/shapes/[shapeKey]/reset" | "/api/admin/shapes/curriculum-defaults" | "/api/admin/shapes/generate" | "/api/geo-ai/ask" | "/api/geo-ai/examples" | "/api/geo-ai/formula-content" | "/api/geo-ai/parse" | "/api/geo-ai/shapes" | "/api/geo-ai/shapes/[shapeKey]" | "/api/geo-ai/shapes/showcase" | "/api/geo-ai/shapes/version" | "/api/geo-ai/tts" | "/api/geogebra/ask" | "/api/geogebra/describe" | "/api/geogebra/exercises" | "/api/geogebra/material" | "/api/geogebra/speak" | "/api/geogebra/suggestions" | "/api/geogebra/tts"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[slug]": { "slug": string; }
  "/admin": {}
  "/api/admin/originals": {}
  "/api/admin/shapes": {}
  "/api/admin/shapes/[shapeKey]": { "shapeKey": string; }
  "/api/admin/shapes/[shapeKey]/rebuild": { "shapeKey": string; }
  "/api/admin/shapes/[shapeKey]/reset": { "shapeKey": string; }
  "/api/admin/shapes/curriculum-defaults": {}
  "/api/admin/shapes/generate": {}
  "/api/geo-ai/ask": {}
  "/api/geo-ai/examples": {}
  "/api/geo-ai/formula-content": {}
  "/api/geo-ai/parse": {}
  "/api/geo-ai/shapes": {}
  "/api/geo-ai/shapes/[shapeKey]": { "shapeKey": string; }
  "/api/geo-ai/shapes/showcase": {}
  "/api/geo-ai/shapes/version": {}
  "/api/geo-ai/tts": {}
  "/api/geogebra/ask": {}
  "/api/geogebra/describe": {}
  "/api/geogebra/exercises": {}
  "/api/geogebra/material": {}
  "/api/geogebra/speak": {}
  "/api/geogebra/suggestions": {}
  "/api/geogebra/tts": {}
  "/geo-v1": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
