// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/geo-v1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/geo-v1">> = Specific
  const handler = {} as typeof import("../../src/app/geo-v1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/originals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/originals">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/originals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/shapes/[shapeKey]/rebuild/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/shapes/[shapeKey]/rebuild">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/shapes/[shapeKey]/rebuild/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/shapes/[shapeKey]/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/shapes/[shapeKey]/reset">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/shapes/[shapeKey]/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/shapes/[shapeKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/shapes/[shapeKey]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/shapes/[shapeKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/shapes/curriculum-defaults/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/shapes/curriculum-defaults">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/shapes/curriculum-defaults/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/shapes/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/shapes/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/shapes/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/shapes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/shapes">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/shapes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo-ai/ask/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo-ai/ask">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo-ai/ask/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo-ai/examples/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo-ai/examples">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo-ai/examples/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo-ai/formula-content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo-ai/formula-content">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo-ai/formula-content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo-ai/parse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo-ai/parse">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo-ai/parse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo-ai/shapes/[shapeKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo-ai/shapes/[shapeKey]">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo-ai/shapes/[shapeKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo-ai/shapes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo-ai/shapes">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo-ai/shapes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo-ai/shapes/showcase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo-ai/shapes/showcase">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo-ai/shapes/showcase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo-ai/shapes/version/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo-ai/shapes/version">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo-ai/shapes/version/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo-ai/tts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo-ai/tts">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo-ai/tts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geogebra/ask/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geogebra/ask">> = Specific
  const handler = {} as typeof import("../../src/app/api/geogebra/ask/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geogebra/describe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geogebra/describe">> = Specific
  const handler = {} as typeof import("../../src/app/api/geogebra/describe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geogebra/exercises/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geogebra/exercises">> = Specific
  const handler = {} as typeof import("../../src/app/api/geogebra/exercises/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geogebra/material/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geogebra/material">> = Specific
  const handler = {} as typeof import("../../src/app/api/geogebra/material/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geogebra/speak/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geogebra/speak">> = Specific
  const handler = {} as typeof import("../../src/app/api/geogebra/speak/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geogebra/suggestions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geogebra/suggestions">> = Specific
  const handler = {} as typeof import("../../src/app/api/geogebra/suggestions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geogebra/tts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geogebra/tts">> = Specific
  const handler = {} as typeof import("../../src/app/api/geogebra/tts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
